name: Release Library
on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  release-lib:
    if: ${{ github.event.pull_request.merged }}
    name: "Release library"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Release lib to PlatformIO
        run: |
          export PLATFORMIO_AUTH_TOKEN=${{ secrets.PLATFORMIO_TOKEN }}
          pio pkg publish --owner gpont --type library --non-interactive

  release-binary:
    if: ${{ github.event.pull_request.merged }}
    permissions: write-all
    name: "Release binary"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build binary
        run: pio pkg pack

      - name: Upload binaries to release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            *.tar.gz
