name: Release Library
on:
  pull_request:
    branches: [master]

jobs:
  release-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Release lib to PlatformIO
        run: |
          export PLATFORMIO_AUTH_TOKEN=${{ secrets.PLATFORMIO_TOKEN }}
          pio pkg publish --owner gpont --type library --non-interactive

  release-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1

      - name: Build binary
        run: pio pkg pack

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EPD_1in9-*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
